### ISSUE TITLE
Confirm Action fails to find alerts

### ISSUE THREAD

**Issue by jimni** [rickypc/robotframework-extendedselenium2library#3]
This is the case where I had to switch back to not-Extended S2L and as a result use both libraries in a single Test Suite which is highly inconvenient.

The code is as follows:

```
Choose Ok On Next Confirmation
Click Link  Delete
Confirm Action
```

The link is a simple bootstrap confirmable anchor:

``` html
<a href="/notifications/133" data-confirm="Are you sure &quot;name&quot;?" data-method="delete" rel="nofollow">Delete</a>
```

What I get with Extended S2L is:
1. confirmation dialog opens,
2. test fails with "There were no alerts".

What is expected (and happens upon changing the library to non-Extended):
1. confirmation dialog opens,
2. "Ok" is clicked inside the dialog.

I would be glad to look into it and try to provide a fix in case this issue becomes confirmed as a bug.

P.s. Other than this little issue the lib is great and has saved me tons of time. Thank you so much, @rickypc.

**Comment by rickypc** [comment]
Hi @jimni,

I created a fiddle to replicate this issue here: https://fiddle.jshell.net/w6sys9nc/15/show/
My test suite is below and I have the latest ExtendedSelenium2Library (0.6.1). The test passed, and from visual inspection, I can see the confirm dialog showed twice and Confirm Action able to close both of them. Please send me any error / debug trace, otherwise. 

```
*** Settings ***
Library  ExtendedSelenium2Library

*** Test Cases ***
Confirm Action Should Not Failed
    Open Browser  https://fiddle.jshell.net/w6sys9nc/15/show/  browser=chrome
    Wait Until Element Is Visible  css=iframe[sandbox^="allow-modals"]
    Select Frame  css=iframe[sandbox^="allow-modals"]
    Wait Until Page Contains  Hello !
    Choose Ok On Next Confirmation
    Click Button  css=input[value="Confirm!"]
    Confirm Action
    Click Link  Delete
    Confirm Action
    Close Browser
```

**Comment by jimni** [comment]
What I failed to locate in the first place is the meaning of @data-method. 
Apparently it is a part of RoR infrastructure (https://github.com/rails/jquery-ujs/wiki/Unobtrusive-scripting-support-for-jQuery#data-method-links-that-result-in-post-put-or-delete-requests). 
I also rechecked visually that OK button does indeed get clicked even in my case.

Looks like the real problem is that after the confirmation no request is sent to the backend (which is RoR ). 

I will try to recreate the environment as best as I can and get back to you with a working example.

**Comment by jimni** [comment]
@rickypc, here is the best I could come up with:

```
*** Settings ***
Library           ExtendedSelenium2Library
Test Teardown  Close Browser

*** Test Cases ***
Test ES2L Without Confirm Action
    Open Browser  http://nikitin.su/s2l_test.html  ff
    Set Selenium Implicit Wait  1
    choose ok on next confirmation
    Click Link  Delete
    Page Should Contain  Method Not Allowed

Test ES2L With Confirm Action
    Open Browser  http://nikitin.su/s2l_test.html  ff
    Set Selenium Implicit Wait  1
    choose ok on next confirmation
    Click Link  Delete
    Confirm Action
    Page Should Contain  Method Not Allowed

Test S2L
    Import Library  Selenium2Library
    Set Library Search Order  Selenium2Library
    Open Browser  http://nikitin.su/s2l_test.html  ff
    choose ok on next confirmation
    Click Link  Delete
    Confirm Action
    Page Should Contain  Method Not Allowed
```

First two tests fail with different reasons. The third passes.

The test page will stay there for at least a few month (jsfiddle failed to host this ugly minified js-cadaver).
Sorry I don't have the original js code. I will consult with my fellow developers but I doubt that they would find my issue worth wasting time on.

This very well could be just me doing something terribly wrong, but I found it curious and a little disturbing that ES2L acted in such a different manner from the original S2L library. I believe my browser fails to construct some fake form and submit it to backend (href target in the case above) is what actually happens.

**Comment by jimni** [comment]
Everything I have mentioned above is true for firefox 43 on osX.

**Comment by rickypc** [comment]
@jimni, I traced down the difference between S2L and ES2L. ES2L is using semi blocking page-ready check on keywords that internally called `Wait Until Angular Ready` keyword. There are two options to skip this behavior. The first can be done globally during library import by specifying `block_until_page_ready=${false}`. The second approach is using the new `skip_ready` argument that I just added in release 0.6.2 . I modified your test-suite example as below. This should give you exactly S2L behavior.

Thank you for spending time to report the issue and please let me know if you still come across any problem.

```
*** Settings ***
Library  ExtendedSelenium2Library
Test Teardown  Close Browser

*** Test Cases ***
Test ES2L Without Confirm Action
    Open Browser  http://nikitin.su/s2l_test.html  ff
    Set Selenium Implicit Wait  1
    Choose Ok On Next Confirmation
    Click Link  Delete  skip_ready=${true}
    Page Should Contain  Method Not Allowed

Test ES2L With Confirm Action
    Open Browser  http://nikitin.su/s2l_test.html  ff
    Set Selenium Implicit Wait  1
    Choose Ok On Next Confirmation
    Click Link  Delete  skip_ready=${true}
    Confirm Action
    Page Should Contain  Method Not Allowed

Test S2L
    Import Library  Selenium2Library
    Set Library Search Order  Selenium2Library
    Open Browser  http://nikitin.su/s2l_test.html  ff
    Choose Ok On Next Confirmation
    Click Link  Delete
    Confirm Action
    Page Should Contain  Method Not Allowed
```

**Comment by jimni** [comment]
Thank you very much for this fix. Looking forward to trying it out as soon as 0.6.2 is available through pip.

Will skip_ready=${true} be specific to Click Link keyword or any other keywords as well? Would it be appropriate to also modify Click Button and Click Element?

**Comment by rickypc** [comment]
@jimni, [0.6.2](https://pypi.python.org/pypi/robotframework-extendedselenium2library/0.6.2) is available in pip, and `skip_ready` also applicable to Click Button, Click Element, etc. Please refer to [documentation](https://rickypc.github.io/robotframework-extendedselenium2library/doc/ExtendedSelenium2Library.html) and search for `skip_ready`

**Comment by jimni** [comment]
Works great, thanks!

**Comment by hannalee8x** [comment]
Hi rickypc,

How to write test case to click on OK from alert popup of mobile app, pls help me !
I'm using robotframework, ride.py

Hanna
