### ISSUE TITLE
It might not be issue but I need to understand little bit more about angular js and selenium 

### ISSUE THREAD

**Issue by jaehokim00** [rickypc/robotframework-extendedselenium2library#4]
instead of biding tag  
<a href="#/queries" class="binding">queries</a>

we do have ng-binding

and html start as   

<a href="#/queries" class="ng-binding">queries</a>  

and it seems that        binding=queries  does not locate the element

**Comment by jaehokim00** [comment]
The properties of the link is following here...

a.ng-binding
accessKey: ""
attributes: NamedNodeMap
baseURI: "http://avata-dev.advertising.aol.com/#/jobs"
charset: ""
childElementCount: 0
childNodes: NodeList[1]
children: HTMLCollection[0]
classList: DOMTokenList[1]
className: "ng-binding"
clientHeight: 54
clientLeft: 0
clientTop: 0
clientWidth: 74
contentEditable: "inherit"
coords: ""
dataset: DOMStringMap
dir: ""
download: ""
draggable: true
firstChild: text
firstElementChild: null
hash: "#/jobs"
hidden: false
host: "avata-dev.advertising.aol.com"
hostname: "avata-dev.advertising.aol.com"
href: "http://avata-dev.advertising.aol.com/#/queries"
hreflang: ""
id: ""
innerHTML: "queries"
innerText: "Queries"
isContentEditable: false
jQuery214094618048099800941: 469
jQuery214094618048099800942: 14
lang: ""
lastChild: text
lastElementChild: null
localName: "a"
name: ""
namespaceURI: "http://www.w3.org/1999/xhtml"
nextElementSibling: null
nextSibling: text
nodeName: "A"
nodeType: 1
nodeValue: null
offsetHeight: 54
offsetLeft: 0
offsetParent: li.ng-scope.active
offsetTop: 0
offsetWidth: 74
onabort: null
onautocomplete: null
onautocompleteerror: null
onbeforecopy: null
onbeforecut: null
onbeforepaste: null
onblur: null
oncancel: null
oncanplay: null
oncanplaythrough: null
onchange: null
onclick: null
onclose: null
oncontextmenu: null
oncopy: null
oncuechange: null
oncut: null
ondblclick: null
ondrag: null
ondragend: null
ondragenter: null
ondragleave: null
ondragover: null
ondragstart: null
ondrop: null
ondurationchange: null
onemptied: null
onended: null
onerror: null
onfocus: null
oninput: null
oninvalid: null
onkeydown: null
onkeypress: null
onkeyup: null
onload: null
onloadeddata: null
onloadedmetadata: null
onloadstart: null
onmousedown: null
onmouseenter: null
onmouseleave: null
onmousemove: null
onmouseout: null
onmouseover: null
onmouseup: null
onmousewheel: null
onpaste: null
onpause: null
onplay: null
onplaying: null
onprogress: null
onratechange: null
onreset: null
onresize: null
onscroll: null
onsearch: null
onseeked: null
onseeking: null
onselect: null
onselectstart: null
onshow: null
onstalled: null
onsubmit: null
onsuspend: null
ontimeupdate: null
ontoggle: null
onvolumechange: null
onwaiting: null
onwebkitfullscreenchange: null
onwebkitfullscreenerror: null
onwheel: null
origin: "http://avata-dev.advertising.aol.com"
outerHTML: "<a href="#/jobs" class="ng-binding">jobs</a>"
outerText: "JOBS"
ownerDocument: document
parentElement: li.ng-scope.active
parentNode: li.ng-scope.active
password: ""
pathname: "/"
ping: ""
port: ""
prefix: null
previousElementSibling: null
previousSibling: text
protocol: "http:"
rel: ""
rev: ""
scrollHeight: 54
scrollLeft: 0
scrollTop: 0
scrollWidth: 74
search: ""
shadowRoot: null
shape: ""
spellcheck: true
style: CSSStyleDeclaration
tabIndex: 0
tagName: "A"
target: ""
text: "jobs"
textContent: "jobs"
title: ""
translate: true
type: ""
username: ""
webkitdropzone: ""

**Comment by rickypc** [comment]
Hi @jaehokim00,

Looking at your link properties, ng-binding is a class name. To use binding strategy, the element need to have either ng-bind property or the rarely seen "ng-bind: expression;" class name. Please see ng-bind documentation: https://docs.angularjs.org/api/ng/directive/ngBind
