### ISSUE TITLE
Query: Is it a good practice to access, an event again on failure, as in snippet below

### ISSUE THREAD

**Issue by SteveHarrison82** [rickypc/robotframework-extendedselenium2library#6]
Hi Ricky,

I just want to understand, is it a good practice to use package as "retrying" and perform an action on failure as below

https://pypi.python.org/pypi/retrying

```
from retrying import retry

.
.
.


@retry(stop_max_attempt_number=3)
def click_button(self, locator, skip_ready=False):
    element = self._scroll_into_view_on_internet_explorer(locator)
    super(ExtendedSelenium2Library, self).click_button(element)
    if not skip_ready:
        self._wait_until_page_ready()
```

**Comment by rickypc** [comment]
Hi @rama-bornfree,
I usually will try to find the root cause on why the element is not clickable at that run time.
_Wait Until Element Is Enabled_ or _Wait Until Element Is Visible_ keyword could be use to sync up with the application.

**Comment by SteveHarrison82** [comment]
Thank you, I will use more of 'wait' methods and try to analyze. 

At times, with the speed at which chrome browser and its driver updates, it becomes difficult to keep up the pace of analyzing the root cause. This is the reason I wished to ask the question

Thank you again
