### ISSUE TITLE
Applitools eyes doesn't work with extendedselenium2library

### ISSUE THREAD

**Issue by SandeepSvanandan** [rickypc/robotframework-extendedselenium2library#7]
When Applitools library is loaded with the frame work, it fails error: Couldn't find Selenium2Library.
Any pointers what can i do it to be fixed or any other alternate.

https://github.com/NaviNet/Robot-AppEyes

**Comment by rickypc** [comment]
Hi @SandeepSvanandan,
I'm not familiar with Applitools eyes, but I believed it is using Selenium2Library internally. You might want to look at their acceptance test file: RobotAppEyesTest.txt on how you need to load all the needed test libraries.
