### ISSUE TITLE
Logging Failure

### ISSUE THREAD

**Issue by jrockefeller** [rickypc/robotframework-extendedselenium2library#9]
Click Element returns the following in the logs instead of the locator.

INFO : Clicking element '<selenium.webdriver.remote.webelement.WebElement (session="f6e2754a836005145dcb174a9b4eddc8", element="0.22097276127897203-5")>'.

Happening on v.0.7.0+

**Comment by rickypc** [comment]
Thank you, @jrockefeller  for reporting the problem. This should be fixed in version 0.9.0. Please reopen otherwise.
